spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_service?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka