server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/heshsandaru/ITS-2118--Software-Architectures-and-Design-Patterns-II.git
          default-label: master
          search-paths:
            - .
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true
