server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
#          uri: -------- add this place your github repo link-------
          default-label: main
          search-paths:
            - .
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true
